using Newtonsoft.Json;
using System;

namespace UniGLTFforUniVgo
{
    /// <summary>
    /// Metadata about the glTF asset.
    /// </summary>
    [Serializable]
    [JsonObject("asset")]
    public class glTFAssets
    {
        /// <summary>A copyright message suitable for display to credit the content creator.</summary>
        [JsonProperty("copyright")]
        public string copyright;

        /// <summary>Tool that generated this glTF model.  Useful for debugging.</summary>
        [JsonProperty("generator")]
        public string generator;

        /// <summary>The glTF version that this asset targets.</summary>
        [JsonProperty("version", Required = Required.Always)]
        //[JsonSchema(Required = true, Pattern = "^[0-9]+\\.[0-9]+$")]
        public string version;

        /// <summary>The minimum glTF version that this asset targets.</summary>
        [JsonProperty("minVersion")]
        //[JsonSchema(Pattern = "^[0-9]+\\.[0-9]+$")]
        public string minVersion;

        /// <summary></summary>
        [JsonProperty("extensions")]
        public object extensions;

        /// <summary></summary>
        [JsonProperty("extras")]
        public object extras;

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return string.Format("GLTF-{0} generated by {1}", version, generator);
        }
    }
}
